export const ACTION_ADD_ITEM = "ACTION_ADD_ITEM";
export const ACTION_REMOVE_ITEM = "ACTION_REMOVE_ITEM";
export const ACTION_LOGIN = {
    ACTION_LOGIN_REQUEST: "ACTION_LOGIN_REQUEST",
    ACTION_LOGIN_SUCCESS: "ACTION_LOGIN_SUCCESS",
    ACTION_LOGIN_FAILED: "ACTION_LOGIN_FAILED",
}
export const ACTION_GET_SHOPS = {
    ACTION_GET_SHOPS_REQUEST: "ACTION_GET_SHOPS_REQUEST",
    ACTION_GET_SHOPS_SUCCESS: "ACTION_GET_SHOPS_SUCCESS",
    ACTION_GET_SHOPS_FAILED: "ACTION_GET_SHOPS_FAILED",
}
export const ACTION_LOADING = {
    LOADING: "LOADING",
    STOP: "STOP"
};
export const ACTION_SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const ACTION_CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const ACTION_TOGGLE_FAVORITE = "ACTION_TOGGLE_FAVORITE";
